name: "Wipe repository"
description: "Remove everything except the .github folder and files inside it. THIS IS VERY DESTRUCTIVE."
branding:
  icon: alert-octagon
  color: red
inputs:
  commit-message:
    description: "Commit message to use when cleaning up the repository"
    required: false
    default: "Wipe repository"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: repo-wipe
      run: cd ${{ github.workspace }} && sudo rm -rf *
      shell: bash
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: ${{ inputs.commit-message }}
